### ISSUE TITLE
getAUJobSummaryController not found

### ISSUE THREAD

**Issue by JNickVA1** [AuthorizeNet/sample-code-csharp#62]
I am trying to compile the sample code and I get an error in GetAccountUpdaterJobSummary.cs because the getAUJobSummaryController type is not found on line 35.

**Comment by binghamrs** [comment]
I have the same error, and I noticed that GetAccountUpdaterJobSummary.cs in the sample code project does not match the version that was committed in GitHub on Aug 1, 2017.  I also get another error when trying to build the sample code project - "SampleCode.exe could not be found".  That may just be due to the fact that the exe could not be built due to the first error, and SampleCodeTest depends on SampleCode.

**Comment by bilderbach** [comment]
Where can we get the info to access the Updater API, I need to get these updates via the API as soon as possible!

I checked the summary, the details and here even the test is commented out:
> //public ANetApiResponse TestGetAccountUpdaterJobSummary()
> //{
> //    return GetAccountUpdaterJobSummary.Run(apiLoginId, transactionKey);
> //}

Is there an updated DLL I should use rather than nuget?

Thanks!

**Comment by Purushottamlpa** [comment]
These were wrong files promoted with the solution. References are removed from project. Please take the latest code (1.9.4), it will build. Confirm us on your progress.
