### ISSUE TITLE
CreateCustomerProfileTransaction method in REST is missing

### ISSUE THREAD

**Issue by ragar005** [AuthorizeNet/sample-code-csharp#68]
SOAP representation of Authorize.Net has CreateCustomerProfileTransaction method and I would like to move to REST API and cannot find this method. Can someone guide me with the equivalent method that is missing in REST

**Comment by adavidw** [comment]
Try this sample:
https://github.com/AuthorizeNet/sample-code-csharp/blob/master/PaymentTransactions/ChargeCustomerProfile.cs

**Comment by adavidw** [comment]
To be more clear, in the newer API, there's not a separate method to do a transaction with a profile. Instead, you call the regular `createTransactionRequest` method, but you pass profile information instead of payment information.

Detailed at the API level here: https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile.

Lots more on customer profiles here: https://developer.authorize.net/api/reference/features/customer_profiles.html

**Comment by ragar005** [comment]
Thanks for the info @adavidw
